site_name: LanceDB Documentation
site_description: LanceDB is a multimodal vector database and search engine.
site_url: https://www.lancedb.com/docs

theme:
  name: material
  icon:
    logo: material/vector-polyline
  palette:
      scheme: slate
      primary: black
  font:
    text: Samurai
    code: Roboto Mono
  features:
    - navigation.path
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - content.code.select
    - content.code.annotate
extra_css:
      - css/custom.css

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true

repo_url: https://github.com/lancedb/docs
repo_name: lancedb/docs


nav:
  - Home: index.md
  - LanceDB:
    - Getting Started:
      - What is LanceDB?: lancedb/getting-started/overview.md
      - Quickstart: lancedb/getting-started/quickstart.md
      - API Reference: lancedb/getting-started/api-reference.md
    - User Guide:
      - Concepts: 
        - Search: lancedb/user-manual/concepts/search.md
        - Tables: lancedb/user-manual/concepts/tables.md
        - Storage: lancedb/user-manual/concepts/storage.md
        - Filtering: lancedb/user-manual/concepts/filtering.md
        - Indexing: lancedb/user-manual/concepts/indexing.md
      - Guides: 
        - Hybrid Search: lancedb/user-manual/guides/hybrid-search.md
        - Multivector Search: lancedb/user-manual/guides/multivector-search.md
  - LanceDB Enterprise:
        - Security: lancedb-enterprise/security.md
  - Build Apps:
      - Developer Portal: build/index.md
  - Articles:
    - Fine-Tuning Embedding Models: articles/fine-tuning-embedding-models.md
  - API Reference: 
    - REST API: api-reference/index.md