site_name: LanceDB Developer Portal
site_description: LanceDB is a multimodal vector database and search engine.
site_url: https://www.lancedb.com/docs

theme:
  name: material
  icon:
    logo: material/vector-polyline
  palette:
      scheme: slate
      primary: black
  font:
    text: Samurai
    code: Roboto Mono
  features:
    - navigation.path
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - toc.follow

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true

repo_url: https://github.com/lancedb/docs
repo_name: lancedb/docs

plugins:
  - search

nav:
  - Documentation: 
    - What is LanceDB?: index.md
    - Quickstart: quickstart.md
    - User Manual:
      - Concepts: 
        - user-manual/concepts/tables.md
        - user-manual/concepts/search.md
        - user-manual/concepts/indexing.md
        - user-manual/concepts/storage.md
      - Guides: 
        - user-manual/guides/hybrid-search.md
        - user-manual/guides/multivector-search.md
        - user-manual/guides/migration.md
        - Reranking:
          - user-manual/guides/reranking/index.md
          - user-manual/guides/reranking/answerdotai.md
          - user-manual/guides/reranking/cohere.md
          - user-manual/guides/reranking/colbert.md
          - user-manual/guides/reranking/cross_encoder.md
          - user-manual/guides/reranking/custom_reranker.md
          - user-manual/guides/reranking/jina.md
          - user-manual/guides/reranking/linear_combination.md
          - user-manual/guides/reranking/openai.md
          - user-manual/guides/reranking/rrf.md
          - user-manual/guides/reranking/voyageai.md
    - Tutorials: 
      - tutorials/tutorial-1.md
      - tutorials/tutorial-2.md
    - Integrations: integrations/index.md
    - API Reference: api/index.md
    - Managed Services:
      - Cloud: managed-services/cloud/index.md
      - Enterprise: managed-services/enterprise/index.md
  - Research: research/index.md
  - Blog: blog/index.md