site_name: LanceDB Documentation
site_url: https://lancedb.com/docs
theme:
  name: material
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.sections
    - navigation.tabs

nav:
  - LanceDB:
    - Getting Started:
      - What is LanceDB?: lancedb/getting-started/overview.md
      - Quickstart: lancedb/getting-started/quickstart.md
      - API Reference: lancedb/getting-started/api-reference.md
    - User Guide:
      - Concepts: 
        - Search: lancedb/user-manual/concepts/search.md
        - Tables: lancedb/user-manual/concepts/tables.md
        - Storage: lancedb/user-manual/concepts/storage.md
        - Filtering: lancedb/user-manual/concepts/filtering.md
        - Indexing: lancedb/user-manual/concepts/indexing.md
      - Guides: 
        - Hybrid Search: lancedb/user-manual/guides/hybrid-search.md
        - Multivector Search: lancedb/user-manual/guides/multivector-search.md
  - LanceDB Enterprise:
    - Security: lancedb-enterprise/security.md
  - API Reference: 
    - REST API: api-reference/index.md
  - Articles:
    - Fine-Tuning Embedding Models: articles/fine-tuning-embedding-models.md
    