site_name: LanceDB Documentation
site_description: LanceDB is a multimodal vector database and search engine.
site_url: https://www.lancedb.com/docs

theme:
  name: material
  custom_dir: overrides
  palette:
      scheme: lancedb
      primary: custom
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - toc.follow
  extra_css:
    - overrides/css/global.css
    - overrides/css/extra.css

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true

repo_url: https://github.com/lancedb/docs
repo_name: lancedb/docs

plugins:
  - search

nav:
  - Documentation: 
    - Documentation: index.md
    - What is LanceDB?: overview/index.md
    - LanceDB Cloud: cloud/index.md
    - Get Started:
      - Quickstart Local: overview/quickstart-local.md
      - Quickstart Cloud: overview/quickstart-cloud.md
    - User Manual:
      - Concepts: 
        - Architecture: concepts/architecture.md
        - Datasets: concepts/datasets.md
        - Vectors: concepts/vectors.md
        - Tables: concepts/tables.md
        - Schema: concepts/schema.md
        - Indexing: concepts/index.md
        - Search: concepts/search.md
        - Filtering: concepts/filtering.md
        - Storage: concepts/storage.md
      - Basic Usage: 
        - Connect to Storage: guides/storage-setup.md
        - Build Hybrid Queries: guides/hybrid-search.md
        - Query Optimization: guides/query-optimization.md
        - Database Configuration: guides/database-configuration.md
        - Migrations: guides/migration.md
      - Advanced Usage:
        - Improve Retrieval:
          - Query Types: guides/tuning_retrievers/1_query_types.md
          - Reranking: guides/tuning_retrievers/2_reranking.md
          - Embedding Tuning: guides/tuning_retrievers/3_embed_tuning.md
    - LanceDB Enterprise: 
      - Overview: 
        - LanceDB Enterprise: enterprise/index.md
        - Architecture: enterprise/architecture.md
        - Deployment: enterprise/deployment.md
        - Benchmarks: enterprise/benchmark.md
        - Security: enterprise/security.md
      - Basic Usage: 
        - Ingest Data: enterprise/guides/ingestion.md
        - Update Data: enterprise/guides/update.md
        - Build an Index: enterprise/guides/build-index.md
        - Vector Search: enterprise/guides/vector-search.md
        - Multivector Search: enterprise/guides/multivector-search.md
        - Full Text Search: enterprise/guides/full-text-search.md
        - Hybrid Search: enterprise/guides/hybrid-search.md
        - Metadata Filtering: enterprise/guides/filtering.md
        - Schema Evolution: enterprise/guides/schema-evolution.md
        - Versioning & Reproducibility: enterprise/guides/versioning.md
        - Query Data with SQL: enterprise/guides/sql-query.md
      - Advanced Usage: 
        - Query Performance Turning: enterprise/guides/understand-query-perf.md
    - Support:
      - FAQ: support/faq-cloud.md
      - Changelog: support/changelog.md
  - Tutorials & Integrations: 
    - Home: tutorials/index.md
    - Basic Tutorials:
      - Build a Chatbot in 5 minutes: tutorials/chatbot.md
      - Build a Wikipedia Search Engine: tutorials/wiki.md
    - Advanced Tutorials:
      - Build a Vector Search App in 5 minutes: tutorials/vector-search-app.md
    - Integrations: 
        - Rerankers:
          - Overview: integrations/rerankers/index.md
          - AnswerDotAI: integrations/rerankers/answerdotai.md
          - Cohere: integrations/rerankers/cohere.md
          - Colbert: integrations/rerankers/colbert.md
          - Cross_encoder: integrations/rerankers/cross_encoder.md
          - Custom_reranker: integrations/rerankers/custom_reranker.md
          - Jina: integrations/rerankers/jina.md
          - Linear_combination: integrations/rerankers/linear_combination.md
          - OpenAI: integrations/rerankers/openai.md
          - RRF: integrations/rerankers/rrf.md
          - VoyageAI: integrations/rerankers/voyageai.md 
        - Embeddings:
          - Overview: integrations/embeddings/index.md
          - Understanding Embeddings: integrations/embeddings/understanding_embeddings.md
          - Custom Embedding Functions: integrations/embeddings/custom_embedding_function.md
          - Default Embedding Functions: integrations/embeddings/default_embedding_functions.md
          - Embedding Functions: integrations/embeddings/embedding_functions.md
          - Variables and Secrets: integrations/embeddings/variables_and_secrets.md
          - Legacy: integrations/embeddings/legacy.md
          - Text Embedding Models:
            - Sentence Transformers: integrations/embeddings/embedding-models/text_embedding_functions/sentence_transformers.md
            - HuggingFace: integrations/embeddings/embedding-models/text_embedding_functions/huggingface_embedding.md
            - Ollama: integrations/embeddings/embedding-models/text_embedding_functions/ollama_embedding.md
            - OpenAI: integrations/embeddings/embedding-models/text_embedding_functions/openai_embedding.md
            - Instructor: integrations/embeddings/embedding-models/text_embedding_functions/instructor_embedding.md
            - Gemini: integrations/embeddings/embedding-models/text_embedding_functions/gemini_embedding.md
            - Cohere: integrations/embeddings/embedding-models/text_embedding_functions/cohere_embedding.md
            - Jina: integrations/embeddings/embedding-models/text_embedding_functions/jina_embedding.md
            - AWS Bedrock: integrations/embeddings/embedding-models/text_embedding_functions/aws_bedrock_embedding.md
            - IBM WatsonX: integrations/embeddings/embedding-models/text_embedding_functions/ibm_watsonx_ai_embedding.md
            - VoyageAI: integrations/embeddings/embedding-models/text_embedding_functions/voyageai_embedding.md
          - Multimodal Embedding Models:
            - OpenCLIP: integrations/embeddings/embedding-models/multimodal_embedding_functions/openclip_embedding.md
            - ImageBind: integrations/embeddings/embedding-models/multimodal_embedding_functions/imagebind_embedding.md
            - Jina Multimodal: integrations/embeddings/embedding-models/multimodal_embedding_functions/jina_multimodal_embedding.md
        - Frameworks:
          - Overview: integrations/frameworks/index.md
          - LangChain: integrations/frameworks/langchain.md
          - LlamaIndex: integrations/frameworks/llamaIndex.md
          - DLT: integrations/frameworks/dlt.md
          - Phidata: integrations/frameworks/phidata.md
          - PromptTools: integrations/frameworks/prompttools.md
          - Voxel51: integrations/frameworks/voxel51.md
  - API & SDK Reference: 
    - Overview: api/index.md
    - Python SDK: api/python-sdk/index.md
    - Javascript SDK (lancedb): api/javascript-sdk/index.md
    - Javascript SDK (vectordb): api/javascript-sdk-vectordb/index.md
    - Rust: https://docs.rs/lancedb/latest/lancedb/index.html
  - Research Studies: research/index.md
  - Blog: https://blog.lancedb.com