site_name: LanceDB Developer Portal
site_description: LanceDB is a multimodal vector database and search engine.
site_url: https://www.lancedb.com/docs

theme:
  name: material
  custom_dir: overrides
  icon:
    logo: material/vector-polyline
  palette:
      scheme: slate
      primary: black
  font:
    text: Samurai
    code: Roboto Mono
  features:
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - toc.follow

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true

repo_url: https://github.com/lancedb/docs
repo_name: lancedb/docs

plugins:
  - search

nav:
  - Documentation: 
    - Homepage: index.md
    - What is LanceDB?: lancedb/index.md
    - LanceDB Enterprise: enterprise/index.md
    - Quickstart: lancedb/quickstart.md
    - User Manual:
      - Concepts: 
        - Data: user-manual/concepts/data.md
        - Vectors: user-manual/concepts/vectors.md
        - Tables: user-manual/concepts/tables.md
        - Schema: user-manual/concepts/schema.md
        - Indexing: user-manual/concepts/index.md
        - Search: user-manual/concepts/search.md
        - Filtering: user-manual/concepts/filtering.md
        - Storage: user-manual/concepts/storage.md
      - How-To Guides: 
        - Connect to Storage: user-manual/guides/storage-setup.md
        - Build Hybrid Queries: user-manual/guides/hybrid-search.md
        - Query Optimization: user-manual/guides/query-optimization.md
        - Database Configuration: user-manual/guides/database-configuration.md
      - Advanced Usage:
        - Rerank Search Results:
          - user-manual/guides/reranking/index.md
          - user-manual/guides/reranking/answerdotai.md
          - user-manual/guides/reranking/cohere.md
          - user-manual/guides/reranking/colbert.md
          - user-manual/guides/reranking/cross_encoder.md
          - user-manual/guides/reranking/custom_reranker.md
          - user-manual/guides/reranking/jina.md
          - user-manual/guides/reranking/linear_combination.md
          - user-manual/guides/reranking/openai.md
          - user-manual/guides/reranking/rrf.md
          - user-manual/guides/reranking/voyageai.md 
        - Improve Retrieval:
          - Query Types: user-manual/guides/tuning_retrievers/1_query_types.md
          - Reranking: user-manual/guides/tuning_retrievers/2_reranking.md
          - Embedding Tuning: user-manual/guides/tuning_retrievers/3_embed_tuning.md
    - Integrations:
      - Embeddings:
        - Overview: integrations/embeddings/index.md
        - Understanding Embeddings: integrations/embeddings/understanding_embeddings.md
        - Custom Embedding Functions: integrations/embeddings/custom_embedding_function.md
        - Default Embedding Functions: integrations/embeddings/default_embedding_functions.md
        - Embedding Functions: integrations/embeddings/embedding_functions.md
        - Variables and Secrets: integrations/embeddings/variables_and_secrets.md
        - Legacy: integrations/embeddings/legacy.md
        - Text Embedding Models:
          - Sentence Transformers: integrations/embeddings/embedding-models/text_embedding_functions/sentence_transformers.md
          - HuggingFace: integrations/embeddings/embedding-models/text_embedding_functions/huggingface_embedding.md
          - Ollama: integrations/embeddings/embedding-models/text_embedding_functions/ollama_embedding.md
          - OpenAI: integrations/embeddings/embedding-models/text_embedding_functions/openai_embedding.md
          - Instructor: integrations/embeddings/embedding-models/text_embedding_functions/instructor_embedding.md
          - Gemini: integrations/embeddings/embedding-models/text_embedding_functions/gemini_embedding.md
          - Cohere: integrations/embeddings/embedding-models/text_embedding_functions/cohere_embedding.md
          - Jina: integrations/embeddings/embedding-models/text_embedding_functions/jina_embedding.md
          - AWS Bedrock: integrations/embeddings/embedding-models/text_embedding_functions/aws_bedrock_embedding.md
          - IBM WatsonX: integrations/embeddings/embedding-models/text_embedding_functions/ibm_watsonx_ai_embedding.md
          - VoyageAI: integrations/embeddings/embedding-models/text_embedding_functions/voyageai_embedding.md
        - Multimodal Embedding Models:
          - OpenCLIP: integrations/embeddings/embedding-models/multimodal_embedding_functions/openclip_embedding.md
          - ImageBind: integrations/embeddings/embedding-models/multimodal_embedding_functions/imagebind_embedding.md
          - Jina Multimodal: integrations/embeddings/embedding-models/multimodal_embedding_functions/jina_multimodal_embedding.md
      - Frameworks:
        - Overview: integrations/frameworks/index.md
        - LangChain: integrations/frameworks/langchain.md
        - LlamaIndex: integrations/frameworks/llamaIndex.md
        - DLT: integrations/frameworks/dlt.md
        - Phidata: integrations/frameworks/phidata.md
        - PromptTools: integrations/frameworks/prompttools.md
        - Voxel51: integrations/frameworks/voxel51.md
    - Support:
      - FAQ: support/faq-cloud.md
  - API & SDK Reference: api/migration.md
  - Research: research/index.md
  - Blog: blog/index.md